fastlane_version ''
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan(
        clean: options[:clean],
        skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
      )
    end


  private_lane :prepare_build_number do
    increment_build_number(
      build_number: ENV['GITHUB_RUN_NUMBER']
    )
  end

  desc "Build archive"
  lane :build do
    prepare_build_number
    gym(
      export_method: "app-store",
      output_directory: "Build",
      output_name: "App.ipa"
    )
  end

  desc "Upload to TestFlight - Internal Tester"
  lane :beta_internal do
    build
    pilot(
      skip_waiting_for_build_processing: false,
      distribute_external: false
    )
  end

end