name: CD - TestFlight Internal

on:
  push:
    branches: [main]      # deploy when you push/merge to main
  workflow_dispatch:       # allow manual runs

concurrency:
  group: cd-internal-${{ github.ref }}
  cancel-in-progress: true

jobs:
  beta-internal:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Provide App Store Connect API key to Fastlane
        run: |
          mkdir -p fastlane
          echo "${APPSTORE_CONNECT_API_KEY_JSON}" > fastlane/api_key.json
        env:
          APPSTORE_CONNECT_API_KEY_JSON: ${{ secrets.APPSTORE_CONNECT_API_KEY_JSON }}

      - name: Fastlane beta_internal
        env:
          APP_STORE_CONNECT_API_KEY_PATH: fastlane/api_key.json
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
        run: bundle exec fastlane beta_internal

      - name: Upload artifacts (ipa & dSYM)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BuildArtifacts
          path: |
            Build/*.ipa
            Build/*.dSYM.zip
          if-no-files-found: ignore
